name: TikTok Auto Upload

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */2 * * *' # Har 2 ghante me run karne ke liye

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install
          npx playwright install chromium --with-deps

      - name: Run TikTok Uploader
        env:
          TIKTOK_COOKIES: ${{ secrets.TIKTOK_COOKIES }}
        run: node tiktok_uploader.js
